version: 2
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y cmake
      - run:
          name: Checkout and build/run check-tidy-misra
          command: buildagent/build.sh
