version: 2
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y cmake
      - run:
          name: Checkout and build/run check-tidy-misra
          command: buildagent/build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
